### ISSUE TITLE
Suggest:

### ISSUE THREAD

**Issue by Kubson6969** [Enzias/EasyDuels#1]
Would be nice to have a feature that allows players bid items like Money Bet, and a system that allows them to have their own , score (so we can setup how mucho points a player will receive or lose when they win or lose a duel) we can setup like at the end of the month players with more scores in their duel stats will recive prizes. (To motivate them to do duels)

And placeholders stats:
examples:
%easyduels_wins%
%easyduels_loses%
%easyduels_score%
%easyduels_rank% (you cant set just in duels a different type of rank depending on your score) if you want.
%easyduels_opponent_hp% (to make a scoreboard when you're in a duel)
%easyduels_opponent_ping%

Not sure if they are good or lot of work for you but do what you can, plugin stills amazing!:D

**Comment by Enzias** [comment]
Hello!
Thank you for the review and for your suggestion.
In the next updates, it is planned that I add the possibility to bet money. The item bet is possible but will take more time to set up so you will still have to wait for it ^^'. Also, it is already planned that I add configurable statistics but I’m still thinking about a good way to implement this.
Placeholders will normally arrive in several weeks when most of the things I have planned will be completed.
Again, thanks for the review and for your good suggestions. I will do my best to ensure that you enjoy future updates.
Have a good day!
