### ISSUE TITLE
Multi Arena

### ISSUE THREAD

**Issue by Akira13345** [Enzias/EasyDuels#14]
A multi arena system would be a good idea, i.e. instead of defining several arenas, there are several fights in the same arena.

Explanation :

Player 1 vs Player 2 in the Sand arena
Player 3 vs Player 4 in the Sand arena

However, the 2 groups will not see this, this prevents the arenas from being full all the time.
Obviously block all interactions between group 1 / group 2.

**Comment by Enzias** [comment]
Thanks for your suggestion, I'll try it! That's a good idea ;)

**Comment by Akira13345** [comment]
Haha thank you, this is never seen in a "/ duel" plugin only used for plugins practice
