### ISSUE TITLE
Suggestion: Dueling Anywhere

### ISSUE THREAD

**Issue by Maitlans** [Enzias/EasyDuels#3]
Would be pretty cool if you could have a config duel outside anywhere, similar to that of World of Warcraft's dueling system where you can request to duel players around you within a border. The popular server Wynncraft also has something like this.

**Comment by Enzias** [comment]
Hello! At the moment, I do not think I am able to make such an update, it will require to rewrite a large part of the plugin. Basically, the plugin requires an arena with coordinates to teleport players. I will see to add this feature but it will probably take several months. 
Nevertheless, if you have a suggestion that could be directly compatible with the arena system do not hesitate, I will do my best to add it to the plugin.
Have a good day ^^
